set_property PACKAGE_PIN P11 [get_ports vn]
set_property PACKAGE_PIN U6 [get_ports rst]
set_property IOSTANDARD SSTL15 [get_ports rst]
set_property PACKAGE_PIN R3 [get_ports clkp]
set_property IOSTANDARD LVDS_25 [get_ports clkp]

set_property MARK_DEBUG true [get_nets {channel[4]}]
set_property MARK_DEBUG true [get_nets {channel[2]}]
set_property MARK_DEBUG true [get_nets {channel[0]}]
set_property MARK_DEBUG true [get_nets {channel[3]}]
set_property MARK_DEBUG true [get_nets {channel[1]}]
set_property MARK_DEBUG true [get_nets {daddr[3]}]
set_property MARK_DEBUG true [get_nets {daddr[5]}]
set_property MARK_DEBUG true [get_nets {daddr[1]}]
set_property MARK_DEBUG true [get_nets {daddr[6]}]
set_property MARK_DEBUG true [get_nets {daddr[4]}]
set_property MARK_DEBUG true [get_nets {daddr[2]}]
set_property MARK_DEBUG true [get_nets {daddr[0]}]
set_property MARK_DEBUG true [get_nets {din[2]}]
set_property MARK_DEBUG true [get_nets {din[3]}]
set_property MARK_DEBUG true [get_nets {din[7]}]
set_property MARK_DEBUG true [get_nets {din[14]}]
set_property MARK_DEBUG true [get_nets {din[11]}]
set_property MARK_DEBUG true [get_nets {din[13]}]
set_property MARK_DEBUG true [get_nets {din[10]}]
set_property MARK_DEBUG true [get_nets {din[4]}]
set_property MARK_DEBUG true [get_nets {din[8]}]
set_property MARK_DEBUG true [get_nets {din[5]}]
set_property MARK_DEBUG true [get_nets {din[9]}]
set_property MARK_DEBUG true [get_nets {din[0]}]
set_property MARK_DEBUG true [get_nets {din[15]}]
set_property MARK_DEBUG true [get_nets {din[12]}]
set_property MARK_DEBUG true [get_nets {din[1]}]
set_property MARK_DEBUG true [get_nets {din[6]}]
set_property MARK_DEBUG true [get_nets {dout[8]}]
set_property MARK_DEBUG true [get_nets {dout[1]}]
set_property MARK_DEBUG true [get_nets {dout[4]}]
set_property MARK_DEBUG true [get_nets {dout[12]}]
set_property MARK_DEBUG true [get_nets {dout[7]}]
set_property MARK_DEBUG true [get_nets {dout[11]}]
set_property MARK_DEBUG true [get_nets {dout[5]}]
set_property MARK_DEBUG true [get_nets {dout[13]}]
set_property MARK_DEBUG true [get_nets {dout[14]}]
set_property MARK_DEBUG true [get_nets {dout[6]}]
set_property MARK_DEBUG true [get_nets {dout[10]}]
set_property MARK_DEBUG true [get_nets {dout[2]}]
set_property MARK_DEBUG true [get_nets {dout[9]}]
set_property MARK_DEBUG true [get_nets {dout[15]}]
set_property MARK_DEBUG true [get_nets {dout[0]}]
set_property MARK_DEBUG true [get_nets {dout[3]}]
set_property MARK_DEBUG true [get_nets busy]
set_property MARK_DEBUG true [get_nets den]
set_property MARK_DEBUG true [get_nets eoc]
set_property MARK_DEBUG true [get_nets dwe]
set_property MARK_DEBUG true [get_nets eos]
set_property MARK_DEBUG true [get_nets drdy]
set_property MARK_DEBUG true [get_nets rst_IBUF]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk200_BUFG]]
set_property port_width 7 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {addr[0]} {addr[1]} {addr[2]} {addr[3]} {addr[4]} {addr[5]} {addr[6]}]]
create_debug_port u_ila_0 probe
set_property port_width 5 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {channel[0]} {channel[1]} {channel[2]} {channel[3]} {channel[4]}]]
create_debug_port u_ila_0 probe
set_property port_width 7 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {daddr[0]} {daddr[1]} {daddr[2]} {daddr[3]} {daddr[4]} {daddr[5]} {daddr[6]}]]
create_debug_port u_ila_0 probe
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {data_in[0]} {data_in[1]} {data_in[2]} {data_in[3]} {data_in[4]} {data_in[5]} {data_in[6]} {data_in[7]} {data_in[8]} {data_in[9]} {data_in[10]} {data_in[11]} {data_in[12]} {data_in[13]} {data_in[14]} {data_in[15]}]]
create_debug_port u_ila_0 probe
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {data_out[0]} {data_out[1]} {data_out[2]} {data_out[3]} {data_out[4]} {data_out[5]} {data_out[6]} {data_out[7]} {data_out[8]} {data_out[9]} {data_out[10]} {data_out[11]} {data_out[12]} {data_out[13]} {data_out[14]} {data_out[15]}]]
create_debug_port u_ila_0 probe
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {din[0]} {din[1]} {din[2]} {din[3]} {din[4]} {din[5]} {din[6]} {din[7]} {din[8]} {din[9]} {din[10]} {din[11]} {din[12]} {din[13]} {din[14]} {din[15]}]]
create_debug_port u_ila_0 probe
set_property port_width 16 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {dout[0]} {dout[1]} {dout[2]} {dout[3]} {dout[4]} {dout[5]} {dout[6]} {dout[7]} {dout[8]} {dout[9]} {dout[10]} {dout[11]} {dout[12]} {dout[13]} {dout[14]} {dout[15]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list busy]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list den]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list drdy]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list dwe]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list eoc]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list eos]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list rd]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list rst_IBUF]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list valid]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list wr]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk200_BUFG]
